platform :ios, '6.0' 
pod 'SHMessageUIBlocks', :path => '../'
pod 'SHNavigationControllerBlocks', :git => "https://github.com/seivan/SHNavigationControllerBlocks.git"


target :ExampleTests do
  pod 'SHTestCaseAdditions', :git => "https://github.com/seivan/SHTestCaseAdditions"
  pod 'SHFastEnumerationProtocols', :git => "https://github.com/PodFactory/SHFastEnumerationProtocols"
  pod "KIF-next"
end